CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
email VARCHAR(254) NOT NULL,
name VARCHAR(250) NOT NULL,
CONSTRAINT pk_users PRIMARY KEY (id),
CONSTRAINT uq_email UNIQUE (email));

CREATE TABLE IF NOT EXISTS categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
name VARCHAR(50) NOT NULL,
CONSTRAINT pk_categories PRIMARY KEY (id),
CONSTRAINT uq_category_name UNIQUE (name));

CREATE TABLE IF NOT EXISTS locations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
lat FLOAT NOT NULL,
lon FLOAT NOT NULL,
CONSTRAINT pk_locations PRIMARY KEY (id));

CREATE TABLE IF NOT EXISTS events (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
title VARCHAR(120) NOT NULL,
annotation VARCHAR(2000) NOT NULL,
description VARCHAR(7000) NOT NULL,
paid BOOLEAN NOT NULL,
request_moderation BOOLEAN NOT NULL,
state VARCHAR(10) NOT NULL,
participant_limit INT NOT NULL,
views BIGINT,
confirmed_requests INT,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
published TIMESTAMP WITHOUT TIME ZONE,
initiator_id BIGINT NOT NULL,
category_id BIGINT NOT NULL,
location_id BIGINT NOT NULL,
CONSTRAINT pk_events PRIMARY KEY (id),
CONSTRAINT fk_events_initiator FOREIGN KEY (initiator_id) REFERENCES users(id) on delete cascade,
CONSTRAINT fk_events_category FOREIGN KEY (category_id) REFERENCES categories(id),
CONSTRAINT fk_events_location FOREIGN KEY (location_id) REFERENCES locations(id));

CREATE TABLE IF NOT EXISTS requests (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
status VARCHAR(10) NOT NULL,
requester_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
CONSTRAINT pk_requests PRIMARY KEY (id),
CONSTRAINT fk_requests_requester FOREIGN KEY (requester_id) REFERENCES users(id),
CONSTRAINT fk_requests_event FOREIGN KEY (event_id) REFERENCES events(id),
CONSTRAINT uq_request UNIQUE (requester_id, event_id));

CREATE TABLE IF NOT EXISTS compilations (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
title VARCHAR(50) NOT NULL,
pinned BOOLEAN NOT NULL,
CONSTRAINT pk_compilations PRIMARY KEY (id),
CONSTRAINT uq_compilation_title UNIQUE (title));

CREATE TABLE IF NOT EXISTS compilation_event (
event_id BIGINT NOT NULL,
compilation_id BIGINT NOT NULL,
CONSTRAINT pk_compilation_event PRIMARY KEY (event_id, compilation_id),
CONSTRAINT fk_compilation_event FOREIGN KEY (event_id) REFERENCES events(id),
CONSTRAINT fk_compilation_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id) on delete cascade);

CREATE TABLE IF NOT EXISTS comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
text VARCHAR(255) NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
event_id BIGINT NOT NULL,
author_id BIGINT NOT NULL,
CONSTRAINT pk_comments PRIMARY KEY(id),
CONSTRAINT fk_comments_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);